<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProductSubcategory2Product', 'doctrine');

/**
 * BaseProductSubcategory2Product
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property integer $product_subcategory_id
 * @property Product $Product
 * @property ProductSubcategory $ProductSubcategory
 * 
 * @method integer                    getProductId()              Returns the current record's "product_id" value
 * @method integer                    getProductSubcategoryId()   Returns the current record's "product_subcategory_id" value
 * @method Product                    getProduct()                Returns the current record's "Product" value
 * @method ProductSubcategory         getProductSubcategory()     Returns the current record's "ProductSubcategory" value
 * @method ProductSubcategory2Product setProductId()              Sets the current record's "product_id" value
 * @method ProductSubcategory2Product setProductSubcategoryId()   Sets the current record's "product_subcategory_id" value
 * @method ProductSubcategory2Product setProduct()                Sets the current record's "Product" value
 * @method ProductSubcategory2Product setProductSubcategory()     Sets the current record's "ProductSubcategory" value
 * 
 * @package    manymoney
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductSubcategory2Product extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_subcategory2product');
        $this->hasColumn('product_id', 'integer', 20, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'comment' => 'Продукт',
             'length' => 20,
             ));
        $this->hasColumn('product_subcategory_id', 'integer', 20, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'comment' => 'Подкатегория',
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ProductSubcategory', array(
             'local' => 'product_subcategory_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}