<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProductSubcategory', 'doctrine');

/**
 * BaseProductSubcategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $product_category_id
 * @property string $announce
 * @property clob $description
 * @property string $alias
 * @property string $image
 * @property boolean $is_active
 * @property ProductCategory $ProductCategory
 * @property Doctrine_Collection $Product
 * @property Doctrine_Collection $ProductSubcategory2Product
 * 
 * @method string              getName()                       Returns the current record's "name" value
 * @method integer             getProductCategoryId()          Returns the current record's "product_category_id" value
 * @method string              getAnnounce()                   Returns the current record's "announce" value
 * @method clob                getDescription()                Returns the current record's "description" value
 * @method string              getAlias()                      Returns the current record's "alias" value
 * @method string              getImage()                      Returns the current record's "image" value
 * @method boolean             getIsActive()                   Returns the current record's "is_active" value
 * @method ProductCategory     getProductCategory()            Returns the current record's "ProductCategory" value
 * @method Doctrine_Collection getProduct()                    Returns the current record's "Product" collection
 * @method Doctrine_Collection getProductSubcategory2Product() Returns the current record's "ProductSubcategory2Product" collection
 * @method ProductSubcategory  setName()                       Sets the current record's "name" value
 * @method ProductSubcategory  setProductCategoryId()          Sets the current record's "product_category_id" value
 * @method ProductSubcategory  setAnnounce()                   Sets the current record's "announce" value
 * @method ProductSubcategory  setDescription()                Sets the current record's "description" value
 * @method ProductSubcategory  setAlias()                      Sets the current record's "alias" value
 * @method ProductSubcategory  setImage()                      Sets the current record's "image" value
 * @method ProductSubcategory  setIsActive()                   Sets the current record's "is_active" value
 * @method ProductSubcategory  setProductCategory()            Sets the current record's "ProductCategory" value
 * @method ProductSubcategory  setProduct()                    Sets the current record's "Product" collection
 * @method ProductSubcategory  setProductSubcategory2Product() Sets the current record's "ProductSubcategory2Product" collection
 * 
 * @package    manymoney
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductSubcategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_subcategory');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'comment' => 'Название подкатегории',
             'length' => 255,
             ));
        $this->hasColumn('product_category_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'comment' => 'ID категории',
             ));
        $this->hasColumn('announce', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Анонс',
             'length' => 1000,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             'comment' => 'Описание',
             ));
        $this->hasColumn('alias', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'comment' => 'Алиас',
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'comment' => 'Изображение',
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             'comment' => 'Элемент активен',
             ));


        $this->index('alias_index', array(
             'fields' => 
             array(
              0 => 'alias',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProductCategory', array(
             'local' => 'product_category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Product', array(
             'refClass' => 'ProductSubcategory2Product',
             'local' => 'product_subcategory_id',
             'foreign' => 'product_id'));

        $this->hasMany('ProductSubcategory2Product', array(
             'local' => 'id',
             'foreign' => 'product_subcategory_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sortable0 = new Doctrine_Template_Sortable();
        $this->actAs($timestampable0);
        $this->actAs($sortable0);
    }
}