<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Manufacturer', 'doctrine');

/**
 * BaseManufacturer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * 
 * @method string       getName() Returns the current record's "name" value
 * @method Manufacturer setName() Sets the current record's "name" value
 * 
 * @package    manymoney
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseManufacturer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('manufacturer');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'comment' => 'Название производителя',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}