generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Product
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          product
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [id, =name, _announce, _image, product_subcategory, manufacturer, quantity_in_stock, cost, is_active, created_at]
        fields:
          created_at: { date_format: dd.MM.yyyy }
        max_per_page: 20
      filter:
        display: [name, product_subcategory_id]
      form:    ~
      edit:    ~
      new:     ~
