<?php

/**
 * ManufacturerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ManufacturerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ManufacturerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Manufacturer');
    }
}