<?php

/**
 * ProductSubcategory2ProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductSubcategory2ProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductSubcategory2ProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductSubcategory2Product');
    }
}