<?php

/**
 * ProductSubcategory2ProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductSubcategory2ProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductSubcategory2ProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductSubcategory2Product');
    }

	public function getBySubcategory($iSubcategoryId) {
		if((int) $iSubcategoryId) {
			$oQuery	= $this->createQuery('ps2p')
								->leftJoin('ps2p.Product p')
								->leftJoin('ps2p.ProductSubcategory ps')
								->where('ps2p.product_subcategory_id = ?', $iSubcategoryId);
			return $oQuery->execute();
		}

		return false;
	}
}