<?php

/**
 * ProductSubcategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductSubcategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductSubcategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductSubcategory');
    }

	public function retrieveProductSubcategoryList() {
		$q = $this->createQuery('ps');

		foreach($q->execute() as $choice){
			$choices[$choice->getId()] = $choice;
		}
		return $choices;
	}
}