<?php

/**
 * ProductCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductCategory');
    }

	public function getActiveList() {
		return $this->createQuery('pc')
			->leftJoin('pc.ProductSubcategory ps')
			->andWhere('pc.is_active = ?', 1)
			->execute();
	}
}