<?php

/**
 * ProductCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductCategory');
    }

	public function getActiveList() {
		return $this->createQuery('pc')
			->andWhere('pc.is_active = ?', 1)
			->execute();
	}

	public function getActiveByAlias($sCategoryAlias = '') {
		if($sCategoryAlias != '') {
			$oQuery		= $this->createQuery('pc')
								->where('pc.alias = ?', $sCategoryAlias)
								->andWhere('pc.is_active = ?', 1);
			return $oQuery->fetchOne();
		}
		return false;
	}
}