<?php

/**
 * StatPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatPageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StatPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StatPage');
    }
}