<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('news', 'announce', 'string', '1000', array(
             'notnull' => '1',
             'comment' => 'Анонс',
             ));
    }

    public function down()
    {

    }
}