<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('product_subcategory', 'product_subcategory_product_category_id_product_category_id', array(
             'name' => 'product_subcategory_product_category_id_product_category_id',
             'local' => 'product_category_id',
             'foreign' => 'id',
             'foreignTable' => 'product_category',
             ));
        $this->addIndex('product_subcategory', 'product_subcategory_product_category_id', array(
             'fields' => 
             array(
              0 => 'product_category_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('product_subcategory', 'product_subcategory_product_category_id_product_category_id');
        $this->removeIndex('product_subcategory', 'product_subcategory_product_category_id', array(
             'fields' => 
             array(
              0 => 'product_category_id',
             ),
             ));
    }
}