<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('product_subcategory', 'product_subcategory_product_category_id_product_category_id', array(
             'name' => 'product_subcategory_product_category_id_product_category_id',
             'local' => 'product_category_id',
             'foreign' => 'id',
             'foreignTable' => 'product_category',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('product_subcategory2product', 'product_subcategory2product_product_id_product_id', array(
             'name' => 'product_subcategory2product_product_id_product_id',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'product',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('product_subcategory2product', 'pppi', array(
             'name' => 'pppi',
             'local' => 'product_subcategory_id',
             'foreign' => 'id',
             'foreignTable' => 'product_subcategory',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('product_subcategory', 'product_subcategory_product_category_id', array(
             'fields' => 
             array(
              0 => 'product_category_id',
             ),
             ));
        $this->addIndex('product_subcategory2product', 'product_subcategory2product_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
        $this->addIndex('product_subcategory2product', 'product_subcategory2product_product_subcategory_id', array(
             'fields' => 
             array(
              0 => 'product_subcategory_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('product_subcategory', 'product_subcategory_product_category_id_product_category_id');
        $this->dropForeignKey('product_subcategory2product', 'product_subcategory2product_product_id_product_id');
        $this->dropForeignKey('product_subcategory2product', 'pppi');
        $this->removeIndex('product_subcategory', 'product_subcategory_product_category_id', array(
             'fields' => 
             array(
              0 => 'product_category_id',
             ),
             ));
        $this->removeIndex('product_subcategory2product', 'product_subcategory2product_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
        $this->removeIndex('product_subcategory2product', 'product_subcategory2product_product_subcategory_id', array(
             'fields' => 
             array(
              0 => 'product_subcategory_id',
             ),
             ));
    }
}