<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('product', 'cost', 'integer', '20', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'autoincrement' => '',
             'notnull' => '1',
             'comment' => 'Цена',
             ));
    }

    public function down()
    {
        $this->removeColumn('product', 'cost');
    }
}