<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('product', 'product_manufacturer_id_manufacturer_id', array(
             'name' => 'product_manufacturer_id_manufacturer_id',
             'local' => 'manufacturer_id',
             'foreign' => 'id',
             'foreignTable' => 'manufacturer',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->addIndex('product', 'product_manufacturer_id', array(
             'fields' => 
             array(
              0 => 'manufacturer_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('product', 'product_manufacturer_id_manufacturer_id');
        $this->removeIndex('product', 'product_manufacturer_id', array(
             'fields' => 
             array(
              0 => 'manufacturer_id',
             ),
             ));
    }
}