<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('product_category', 'alias_index', array(
             'fields' => 
             array(
              0 => 'alias',
             ),
             'type' => 'unique',
             ));
        $this->addIndex('product_subcategory', 'alias_index', array(
             'fields' => 
             array(
              0 => 'alias',
             ),
             'type' => 'unique',
             ));
    }

    public function down()
    {
        $this->removeIndex('product_category', 'alias_index', array(
             'fields' => 
             array(
              0 => 'alias',
             ),
             'type' => 'unique',
             ));
        $this->removeIndex('product_subcategory', 'alias_index', array(
             'fields' => 
             array(
              0 => 'alias',
             ),
             'type' => 'unique',
             ));
    }
}