<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('product', 'manufacturer_id', 'integer', '20', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'autoincrement' => '',
             'notnull' => '',
             'comment' => 'Производитель',
             ));
    }

    public function down()
    {
        $this->removeColumn('product', 'manufacturer_id');
    }
}