StatPage:
  connection: doctrine
  comment: 'Статические страницы'
  tableName: stat_page
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
      comment: 'Заголовок страницы'
    alias:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
      comment: 'Символьное имя страницы'
    description:
      type: clob
      notnull: true
      comment: 'Текст страницы'
    image:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
      comment: 'Изображение'

News:
  connection: doctrine
  comment: 'Новости'
  tableName: news
  actAs:
    Timestampable: ~
    Sortable: ~
  columns:
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
      comment: 'Заголовок новости'
    announce:
      type: string(1000)
      notnull: true
      comment: 'Анонс'
    description:
      type: clob
      notnull: true
      comment: 'Описание'
    image:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
      comment: 'Изображение'
    is_active:
      type: boolean
      notnull: true
      default: true
      comment: 'Элемент активен'

ProductCategory:
  connection: doctrine
  comment: 'Категории продуктов'
  tableName: product_category
  actAs:
    Timestampable: ~
    Sortable: ~
  columns:
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
      comment: 'Название категории'
    announce:
      type: string(1000)
      notnull: true
      comment: 'Анонс'
    description:
      type: clob
      notnull: true
      comment: 'Описание'
    alias:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
      comment: 'Алиас'
    image:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
      comment: 'Изображение'
    is_active:
      type: boolean
      notnull: true
      default: true
      comment: 'Элемент активен'
  indexes:
    alias_index:
      fields: [alias]
      type: unique

ProductSubcategory:
  connection: doctrine
  comment: 'Подкатегории продуктов'
  tableName: product_subcategory
  actAs:
    Timestampable: ~
    Sortable: ~
  columns:
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
      comment: 'Название подкатегории'
    product_category_id:
      type: integer
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
      comment: 'ID категории'
    announce:
      type: string(1000)
      notnull: true
      comment: 'Анонс'
    description:
      type: clob
      notnull: true
      comment: 'Описание'
    alias:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
      comment: 'Алиас'
    image:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
      comment: 'Изображение'
    is_active:
      type: boolean
      notnull: true
      default: true
      comment: 'Элемент активен'
  relations:
    ProductCategory:
      type: one
      local: product_category_id
      class: ProductCategory
      foreign: id
      onDelete: CASCADE
  indexes:
    alias_index:
      fields: [alias]
      type: unique

Product:
  connection: doctrine
  comment: 'Продукты'
  tableName: product
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
      comment: 'Название продукта'
    announce:
      type: string(1000)
      notnull: true
      comment: 'Анонс'
    description:
      type: clob
      notnull: true
      comment: 'Описание'
    image:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
      comment: 'Изображение'
    is_active:
      type: boolean
      notnull: true
      default: true
      comment: 'Элемент активен'
    quantity_in_stock:
      type: integer(20)
      fixed: false
      unsigned: false
      primary: false
      autoincrement: false
      notnull: true
      comment: 'Количество на складе'
    cost:
      type: integer(20)
      fixed: false
      unsigned: false
      primary: false
      autoincrement: false
      notnull: true
      comment: 'Цена'
    manufacturer_id:
      type: integer(20)
      fixed: false
      unsigned: false
      primary: false
      autoincrement: false
      notnull: false
      comment: 'Производитель'
  relations:
    ProductSubcategory:
      class: ProductSubcategory
      refClass: ProductSubcategory2Product
      local: product_id
      foreign: product_subcategory_id
    Manufacturer:
      local: manufacturer_id
      foreign: id
      type: one
      class: Manufacturer
      onDelete: SET NULL

ProductSubcategory2Product:
  connection: doctrine
  comment: 'Связка продуктов и подкатегорий'
  tableName: product_subcategory2product
  actAs:
    Timestampable: ~
  columns:
    product_id:
      type: integer(20)
      fixed: false
      unsigned: false
      primary: false
      autoincrement: false
      comment: 'Продукт'
    product_subcategory_id:
      type: integer(20)
      fixed: false
      unsigned: false
      primary: false
      autoincrement: false
      comment: 'Подкатегория'
  relations:
    Product:
      local: product_id
      foreign: id
      type: one
      class: Product
      onDelete: CASCADE
    ProductSubcategory:
      local: product_subcategory_id
      foreign: id
      type: one
      class: ProductSubcategory
      onDelete: CASCADE

Manufacturer:
  connection: doctrine
  comment: 'Производитель'
  tableName: manufacturer
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
      comment: 'Название производителя'

Product2Product:
  connection: doctrine
  comment: 'Связка товара с товаром'
  tableName: product2product
  columns:
    product_id:
      type: integer(20)
      fixed: false
      unsigned: false
      primary: false
      autoincrement: false
      comment: 'Продукт 1'
    parent_product_id:
      type: integer(20)
      fixed: false
      unsigned: false
      primary: false
      autoincrement: false
      comment: 'Продукт 2'
  relations:
    Product:
      local: product_id
      foreign: id
      type: one
      class: Product
      onDelete: CASCADE
    ParentProduct:
      local: parent_product_id
      foreign: id
      type: one
      class: Product
      onDelete: CASCADE
  indexes:
    product2product_index:
      fields: [product_id, parent_product_id]
      type: unique